### PR TITLE
Upgrade apisauce

### PR DESCRIPTION
**Pull request by elyobo**
Updates axios for security fixes

### CODE REVIEW

**Comment by GantMan** [comment]
thanks!

**Comment by elyobo** [comment]
Any plans for a release on this soon @GantMan?

**Comment by GantMan** [comment]
Would you like to be an admin on the repo and NPM?  I'd love help from someone who's actively using it!

**Comment by elyobo** [comment]
I'm not actively using it yet, so I'm probably not a good admin sorry - I was looking at using https://github.com/SudoPlz/sp-react-native-in-app-updates however the security issues mentioned in https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/191 seemed like a blocker.

**Pull request merged**
