### PR TITLE
add the ability to pass options (such a forceUpdate)

### PR DESCRIPTION
**Pull request by reimertz**
- title
- message
- buttonUpdateText
- buttonCancelText
- forceUpdate

### CODE REVIEW

**Comment by reimertz** [comment]
thinking about adding versionMap feature where you can set different options for different versions. What do you think about that @GantMan?

**Comment by GantMan** [comment]
Good to see ya @reimertz !!!!!!

BTW, do you want rights to publish?

**Comment by reimertz** [comment]
Good to see you too @gantman! 

Shit, you just merged it, where you able to test it before merging? I was just about to test it with our app, but haven;t actually tested it (at all!)  😅

**Comment by GantMan** [comment]
I didn't test either.  It's all good.  I won't push a new NPM until it's been tested.

But that's also why I ask.  If it works, would you like to have rights to publish to NPM etc.?

**Comment by reimertz** [comment]
Sure, that would be nice! I promise to be nice. Maybe even write a test (or two)!<3

**Comment by GantMan** [comment]
hahaha for sure.  What's your NPM username?

**Comment by GantMan** [comment]
nm, I found ya reimertz everywhere!

**Pull request merged**
